/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./components/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TableSkeleton: typeof import('./components/loading/TableSkeleton.vue')['default']
    TeacherForm: typeof import('./components/TeacherForm.vue')['default']
  }
}
